<?xml version="1.0" encoding="utf-8"?><Database Name="TLBD" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=JARVIZ;Initial Catalog=TLBD;Persist Security Info=True;User ID=guest" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TLBDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Alumno" Member="Alumno">
    <Type Name="Alumno">
      <Column Name="IDAlumno" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NoControl" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="ApPaterno" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="ApMaterno" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Carrera" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Association Name="Alumno_Sesion" Member="Sesion" ThisKey="IDAlumno" OtherKey="IDAlumno" Type="Sesion" />
    </Type>
  </Table>
  <Table Name="dbo.Docente" Member="Docente">
    <Type Name="Docente">
      <Column Name="IDDoc" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RFC" Type="System.String" DbType="NVarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="DNombre" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="DApPaterno" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="DApMaterno" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Association Name="Docente_Sesion" Member="Sesion" ThisKey="IDDoc" OtherKey="IDDoc" Type="Sesion" />
    </Type>
  </Table>
  <Table Name="dbo.Materia" Member="Materia">
    <Type Name="Materia">
      <Column Name="IDMat" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Creditos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Association Name="Materia_Sesion" Member="Sesion" ThisKey="IDMat" OtherKey="IDMat" Type="Sesion" />
      <Association Name="Materia_Tarea" Member="Tarea" ThisKey="IDMat" OtherKey="IDMat" Type="Tarea" />
    </Type>
  </Table>
  <Table Name="dbo.Periodo" Member="Periodo">
    <Type Name="Periodo">
      <Column Name="IDPeriodo" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FechaInicio" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaCierre" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Sesion" Member="Sesion">
    <Type Name="Sesion">
      <Column Name="IDSesion" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IDAlumno" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IDDoc" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IDMat" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Aula" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Association Name="Alumno_Sesion" Member="Alumno" ThisKey="IDAlumno" OtherKey="IDAlumno" Type="Alumno" IsForeignKey="true" />
      <Association Name="Docente_Sesion" Member="Docente" ThisKey="IDDoc" OtherKey="IDDoc" Type="Docente" IsForeignKey="true" />
      <Association Name="Materia_Sesion" Member="Materia" ThisKey="IDMat" OtherKey="IDMat" Type="Materia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tarea" Member="Tarea">
    <Type Name="Tarea">
      <Column Name="IDTareas" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDMat" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Titulo" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FechaEntrega" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Materia_Tarea" Member="Materia" ThisKey="IDMat" OtherKey="IDMat" Type="Materia" IsForeignKey="true" />
    </Type>
  </Table>
</Database>