//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calculadora.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSuma", ReplyAction="http://tempuri.org/IService1/GetSumaResponse")]
        float GetSuma(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSuma", ReplyAction="http://tempuri.org/IService1/GetSumaResponse")]
        System.Threading.Tasks.Task<float> GetSumaAsync(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetResta", ReplyAction="http://tempuri.org/IService1/GetRestaResponse")]
        float GetResta(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetResta", ReplyAction="http://tempuri.org/IService1/GetRestaResponse")]
        System.Threading.Tasks.Task<float> GetRestaAsync(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDividir", ReplyAction="http://tempuri.org/IService1/GetDividirResponse")]
        float GetDividir(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDividir", ReplyAction="http://tempuri.org/IService1/GetDividirResponse")]
        System.Threading.Tasks.Task<float> GetDividirAsync(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProducto", ReplyAction="http://tempuri.org/IService1/GetProductoResponse")]
        float GetProducto(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProducto", ReplyAction="http://tempuri.org/IService1/GetProductoResponse")]
        System.Threading.Tasks.Task<float> GetProductoAsync(float a, float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        calculadora.ServiceReference1.CompositeType GetDataUsingDataContract(calculadora.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<calculadora.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(calculadora.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : calculadora.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<calculadora.ServiceReference1.IService1>, calculadora.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public float GetSuma(float a, float b) {
            return base.Channel.GetSuma(a, b);
        }
        
        public System.Threading.Tasks.Task<float> GetSumaAsync(float a, float b) {
            return base.Channel.GetSumaAsync(a, b);
        }
        
        public float GetResta(float a, float b) {
            return base.Channel.GetResta(a, b);
        }
        
        public System.Threading.Tasks.Task<float> GetRestaAsync(float a, float b) {
            return base.Channel.GetRestaAsync(a, b);
        }
        
        public float GetDividir(float a, float b) {
            return base.Channel.GetDividir(a, b);
        }
        
        public System.Threading.Tasks.Task<float> GetDividirAsync(float a, float b) {
            return base.Channel.GetDividirAsync(a, b);
        }
        
        public float GetProducto(float a, float b) {
            return base.Channel.GetProducto(a, b);
        }
        
        public System.Threading.Tasks.Task<float> GetProductoAsync(float a, float b) {
            return base.Channel.GetProductoAsync(a, b);
        }
        
        public calculadora.ServiceReference1.CompositeType GetDataUsingDataContract(calculadora.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<calculadora.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(calculadora.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
